# 异常、断言、日志和调试
## 1. 异常
### 1. 异常分类
- 未检查异常：派生与Error类或RuntimeException类的所有异常。
- 已检查异常：所有其他异常。

### 2. 捕获异常
- 如果在try语句块中抛出了一个catch子句中说明的异常时，
	- 程序将跳过try语句块其余代码。
	- 程序将执行catch子句中的处理器代码。
- 如果在try语句块中没有抛出任何异常，程序将跳过catch。
- 如果try语句块中方法抛出一个在catch中没有说明的异常时，方法会立刻退出。
- 不允许在子类的throws说明符中出现超过超类方法所列出的异常类范围。

### 3. finally子句
- 如果代码中没有抛出异常，程序会执行所有try中代码，再执行finally中代码，再执行try/catch之后的代码。
- 如果抛出了一个在catch子句中捕获的异常，程序会执行try中代码直到发生异常，再执行匹配的catch的代码，再执行finally的代码，
	- 如果catch语句没有抛出异常，程序将执行try/catch后的代码。
	- 如果catch语句抛出异常，异常将被抛回给这个方法的调用者，不执行try/catch之后的代码。
- 如果抛出了一个没有在catch中捕获的异常，程序将执行try中代码直到发生异常，再执行finally中的代码，并将异常抛回给调用者，不执行try/catch之后代码。
- 当finally中有return语句时，它将替代try/catch语句块中的return语句。
- 当finally语句块中的代码抛出异常时，原始的异常将丢失，转而抛出finally中的异常。

### 4. 带资源的try语句（Java SE 7）
```java
try（Scanner in = new Scanner(****);PrintWriter out = new PrintWriter(***)){
	*****
}
```
- 不管try正常退出或者抛出异常，in和close都会关闭。
- 如果close方法（原finally语句块）也抛出一个异常时，原来的异常会重新抛出，而close方法抛出的异常会被抑制。这些异常会自动捕获，并由addSuppressed方法增加到原来的异常。可以调用getSuppressed方法，它会的到从close方法抛出并被抑制的异常列表。

## 2.断言
- 关键字：assert的两种形式：assert 条件，assert 条件：表达式。
- 对条件检测，如果结果为false，抛出AssertionError异常，表达式会被传入AssertionError构造器，并转换成一个消息字符串。
- AssertionError对象不存储表达式的值，所以不能得到它。

## 3. 调试技巧
- 打印变量的值
- 单元测试